-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 18:52:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema travel_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_db
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS travel_db DEFAULT CHARACTER SET utf8;
USE travel_db;

-- =====================
-- COUNTRIES
-- =====================
CREATE TABLE countries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT
) ENGINE=InnoDB;

-- =====================
-- TOURS
-- =====================
CREATE TABLE tours (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  country_id INT NOT NULL,
  description TEXT,
  duration_days INT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  INDEX idx_country_id (country_id),

  CONSTRAINT fk_tours_country
    FOREIGN KEY (country_id)
    REFERENCES countries(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =====================
-- TOUR DATES
-- =====================
CREATE TABLE tour_dates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tour_id INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  total_slots INT NOT NULL,
  booked_slots INT NOT NULL,

  INDEX idx_tour_id (tour_id),

  CONSTRAINT fk_tour_dates_tour
    FOREIGN KEY (tour_id)
    REFERENCES tours(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =====================
-- USERS
-- =====================
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(45) NOT NULL DEFAULT 'user',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- =====================
-- REVIEWS
-- =====================
CREATE TABLE reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  tour_id INT NOT NULL,
  rating INT NOT NULL,
  review VARCHAR(1000) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_user_id (user_id),
  INDEX idx_tour_id (tour_id),

  CONSTRAINT fk_reviews_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,

  CONSTRAINT fk_reviews_tour
    FOREIGN KEY (tour_id)
    REFERENCES tours(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =====================
-- REQUESTS
-- =====================
CREATE TABLE requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tour_date_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  comment VARCHAR(255),
  status ENUM('new','contacted','confirmed','cancelled') DEFAULT 'new',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  INDEX idx_tour_date_id (tour_date_id),

  CONSTRAINT fk_requests_tour_date
    FOREIGN KEY (tour_date_id)
    REFERENCES tour_dates(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
) ENGINE=InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
